sonata_user:
    class:
        user: App\Entity\SonataUserUser
        group: App\Entity\SonataUserGroup

    admin:                  # Admin Classes
        user:
            class:           App\Admin\UserAdmin
            #class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            #controller:     Sonata\AdminBundle\Controller\CRUDController
            translation:    SonataUserBundle