sonata_admin:
    title: 'ACO - Sistema'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        #groups:
        #    DASHBOARD:
        #        label: Dashboards
        #        items: 
        #            - route: sonata_admin_dashboard
        #              label: AI ACO (Dashboard)
        #    DASHBOARD1:
        #        label: Dashboards
        #        items: 
        #            - route: sonata_admin_dashboard
        #              label: AI ACO (Dashboard)
        #            - route: dashboard1
        #              label: AI ACO (Dashboard1)
        #    Clientes:
        #        label:                Clientes
        #        items:
        #            - admin.uso_cfdi
        #            - admin.tipo_domicilio
        #            - admin.formas_pago
        #        roles: ['ROLE_ADMIN', 'ROLE_SONATA_ADMIN']
        #    RRHH:
        #        label:                RRHH
        #        items:
        #            - route: admin_app_sonatausergroup_list
        #              label: Grupos
        #              roles:        ['ROLE_ADMIN', 'ROLE_SONATA_ADMIN']
        #            - sonata.user.admin.group
        #            - admin.puesto
        #            - admin.tipo_sangre
        #            - admin.estado_civil
        #            - admin.user_funcion
        #            - admin.tipos_licencia
        #        roles: ['ROLE_ADMIN', 'ROLE_SONATA_ADMIN']
        #    Compras:
        #        label:                Compras
        #        items:
        #            - admin.formas_pago
        #            - admin.bancos
        #            - admin.estatus_pago
        #            - admin.almacenajes
        #        roles: ['ROLE_ADMIN', 'ROLE_SONATA_ADMIN']
        #    Ventas:
        #        label:                Ventas
        #        items:
        #            - admin.metodos_pago
        #        roles: ['ROLE_ADMIN', 'ROLE_SONATA_ADMIN']
        #    Otros:
        #        label:                Otros
        #        items:
        #            - admin.municipios
        #            - admin.estados
        #            - admin.paises
        #        roles: ['ROLE_ADMIN', 'ROLE_SONATA_ADMIN']
    templates:
        layout:                     '@SonataAdmin/standard_layout.html.twig'
        ajax:                       '@SonataAdmin/ajax_layout.html.twig'
        list:                       '@SonataAdmin/CRUD/list.html.twig'
        show:                       '@SonataAdmin/CRUD/show.html.twig'
        show_compare:               '@SonataAdmin/CRUD/show_compare.html.twig'
        edit:                       '@SonataAdmin/CRUD/edit.html.twig'
        history:                    '@SonataAdmin/CRUD/history.html.twig'
        preview:                    '@SonataAdmin/CRUD/preview.html.twig'
        delete:                     '@SonataAdmin/CRUD/delete.html.twig'
        batch:                      '@SonataAdmin/CRUD/list__batch.html.twig'
        acl:                        '@SonataAdmin/CRUD/acl.html.twig'
        action:                     '@SonataAdmin/CRUD/action.html.twig'
        select:                     '@SonataAdmin/CRUD/list__select.html.twig'
        filter:                     '@SonataAdmin/Form/filter_admin_fields.html.twig'
        dashboard:                  'home/dashboard.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
            