sonata_admin:
    title: 'ACO - Sistema'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        layout:                     '@SonataAdmin/standard_layout.html.twig'
        ajax:                       '@SonataAdmin/ajax_layout.html.twig'
        list:                       '@SonataAdmin/CRUD/list.html.twig'
        show:                       '@SonataAdmin/CRUD/show.html.twig'
        show_compare:               '@SonataAdmin/CRUD/show_compare.html.twig'
        edit:                       '@SonataAdmin/CRUD/edit.html.twig'
        history:                    '@SonataAdmin/CRUD/history.html.twig'
        preview:                    '@SonataAdmin/CRUD/preview.html.twig'
        delete:                     '@SonataAdmin/CRUD/delete.html.twig'
        batch:                      '@SonataAdmin/CRUD/list__batch.html.twig'
        acl:                        '@SonataAdmin/CRUD/acl.html.twig'
        action:                     '@SonataAdmin/CRUD/action.html.twig'
        select:                     '@SonataAdmin/CRUD/list__select.html.twig'
        filter:                     '@SonataAdmin/Form/filter_admin_fields.html.twig'
        dashboard:                  'home/dashboard.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
            