sonata_intl:
    timezone:
        default: America/Mexico_City
        locales:
            es_MX:    America/Mexico_City
            en: America/Denver
        detectors:
            - sonata.intl.timezone_detector.user
            - sonata.intl.timezone_detector.locale