vich_uploader:
    db_driver: orm

    mappings:
        domicilio_image:
            uri_prefix: /files/domicilio
            upload_destination: '%kernel.project_dir%/public/files/domicilio'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        rfc_image:
            uri_prefix: /files/rfc
            upload_destination: '%kernel.project_dir%/public/files/rfc'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        curp_image:
            uri_prefix: /files/curp
            upload_destination: '%kernel.project_dir%/public/files/curp'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        fotografia_image:
            uri_prefix: /files/fotografia
            upload_destination: '%kernel.project_dir%/public/files/fotografia'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer