# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: sp_MX

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #admin.regisro_clave:
    #    class: App\Admin\RegisroClaveAdmin
    #    arguments: [~, App\Entity\RegisroClave, ~]
    #    tags:
    #        - { name: sonata.admin, manager_type: orm, group: Administración, label: Registro de Claves }
    #    public: true

    fos_user.registration.controller: 
        class: App\Controller\UserBundle\RegistrationController  

    FOS\UserBundle\Form\Factory\FactoryInterface: '@fos_user.registration.form.factory'

    admin_success_handler:
        class: App\Services\AuthenticationHandler
        arguments: [ '@service_container' ]

    #https://symfony.com/doc/current/bundles/SonataAdminBundle/cookbook/recipe_knp_menu.html
    app.menu_listener:
        class: App\EventListener\MenuBuilderListener
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    admin.puesto:
        class: App\Admin\PuestoAdmin
        arguments: [~, App\Entity\Puesto, App\Controller\PuestoAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Puesto }
        public: true

    admin.tipo_sangre:
        class: App\Admin\TipoSangreAdmin
        arguments: [~, App\Entity\TipoSangre, App\Controller\TipoSangreAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Tipo de Sangre }
        public: true

    admin.estado_civil:
        class: App\Admin\EstadoCivilAdmin
        arguments: [~, App\Entity\EstadoCivil, App\Controller\EstadoCivilAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Estado Civil }
        public: true

    admin.salario:
        class: App\Admin\SalarioAdmin
        arguments: [~, App\Entity\Salario, App\Controller\SalarioController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Salario }
        public: true

    admin.clientes:
        class: App\Admin\ClientesAdmin
        arguments: [~, App\Entity\Clientes, App\Controller\ClientesController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administración, label: Clientes }
        public: true

    admin.tipo_domicilio:
        class: App\Admin\TipoDomicilioAdmin
        arguments: [~, App\Entity\TipoDomicilio, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administración, label: TipoDomicilio }
        public: true

    admin.domicilios:
        class: App\Admin\DomiciliosAdmin
        arguments: [~, App\Entity\Domicilios, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administración, label: Domicilios }
        public: true

    admin.cliente_contactos:
        class: App\Admin\ClienteContactosAdmin
        arguments: [~, App\Entity\ClienteContactos, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administración, label: ClienteContactos }
        public: false

    admin.uso_cfdi:
        class: App\Admin\UsoCfdiAdmin
        arguments: [~, App\Entity\UsoCfdi, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administración, label: UsoCfdi }
        public: true

    admin.user_funcion:
        class: App\Admin\UserFuncionAdmin
        arguments: [~, App\Entity\UserFuncion, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: UserFuncion }
        public: true
        
    admin.productos:
        class: App\Admin\ProductosAdmin
        arguments: [~, App\Entity\Productos, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Productos }
        public: true

    admin.formas_pago:
        class: App\Admin\FormasPagoAdmin
        arguments: [~, App\Entity\FormasPago, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: FormasPago }
        public: true

    admin.bancos:
        class: App\Admin\BancosAdmin
        arguments: [~, App\Entity\Bancos, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Bancos }
        public: true

    admin.estatus_pago:
        class: App\Admin\EstatusPagoAdmin
        arguments: [~, App\Entity\EstatusPago, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: EstatusPago }
        public: true

    admin.almacenajes:
        class: App\Admin\AlmacenajesAdmin
        arguments: [~, App\Entity\Almacenajes, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Almacenajes }
        public: true

    admin.compras:
        class: App\Admin\ComprasAdmin
        arguments: [~, App\Entity\Compras, App\Controller\ComprasController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Compras }
        public: true
        calls:
            - [ setTemplate, [edit, compras/edit.html.twig]]

    admin.proveedores:
        class: App\Admin\ProveedoresAdmin
        arguments: [~, App\Entity\Proveedores, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Proveedores }
        public: true

    admin.proveedor_contactos:
        class: App\Admin\ProveedorContactosAdmin
        arguments: [~, App\Entity\ProveedorContactos, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: ProveedorContactos }
        public: false
